# Generated by Django 4.2.3 on 2024-05-17 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_platform', '0004_remove_student_user_remove_customuser_is_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='intern',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internship',
        ),
        migrations.AddField(
            model_name='application',
            name='internship_opportunity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='intern_platform.internship'),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
