# Generated by Django 4.2.13 on 2024-05-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_platform', '0007_internprofile_additional_email_internprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internprofile',
            old_name='address',
            new_name='street_address2',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='internprofile',
            name='university',
        ),
        migrations.AddField(
            model_name='internprofile',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='additional_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='marital_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year_passout', models.CharField(max_length=4)),
                ('course', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_background', to='intern_platform.internprofile')),
            ],
        ),
    ]
