# Generated by Django 4.2.13 on 2024-05-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_platform', '0008_rename_address_internprofile_street_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='additional_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='street_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='street_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='marital_status',
            field=models.CharField(default='single', max_length=10),
        ),
    ]
