# Generated by Django 4.2.13 on 2024-05-24 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intern_platform', '0009_employerprofile_additional_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='apply_before',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='experience',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='qualification',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='role_required',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='skills_preferred',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
