# Generated by Django 4.2.13 on 2024-05-25 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_platform', '0012_alter_internship_apply_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='apply_before',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='internship_area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='internship_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
